import SwiftUI

struct Acknowledgement: Codable, Identifiable {
    let name: String
    let version: String
    let url: String
    let license: String
    let licenseText: String
    let notice: String?

    var id: String { name }

    /// Loads the bundled list generated by `make licenses`. Returns an empty list if it is missing or malformed.
    static func loadBundled(from bundle: Bundle = .main) -> [Acknowledgement] {
        guard let url = bundle.url(forResource: "Acknowledgements", withExtension: "json"),
            let data = try? Data(contentsOf: url),
            let items = try? JSONDecoder().decode([Acknowledgement].self, from: data)
        else { return [] }
        return items
    }
}

struct AcknowledgementsView: View {
    @Environment(\.dismiss) private var dismiss
    private let items = Acknowledgement.loadBundled()

    var body: some View {
        NavigationStack {
            List(items) { item in
                NavigationLink {
                    ScrollView {
                        VStack(alignment: .leading, spacing: 12) {
                            Text(item.license).font(.headline)
                            if let notice = item.notice {
                                Text(notice).font(.caption.monospaced())
                            }
                            Text(item.licenseText).font(.caption.monospaced())
                        }
                        .frame(maxWidth: .infinity, alignment: .leading)
                        .padding()
                    }
                    .navigationTitle(item.name)
                    .navigationBarTitleDisplayMode(.inline)
                } label: {
                    VStack(alignment: .leading) {
                        Text(item.name)
                        Text("\(item.version) · \(item.license)")
                            .font(.caption)
                            .foregroundStyle(.secondary)
                    }
                }
                .accessibilityIdentifier("acknowledgements.row.\(item.name)")
            }
            .navigationTitle("Acknowledgements")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .confirmationAction) {
                    Button("Done") { dismiss() }
                        .accessibilityIdentifier("acknowledgements.done")
                }
            }
        }
    }
}
