#!/usr/bin/env bash
# Generates THIRD-PARTY-LICENSES.md and FoodPlanner/Resources/Acknowledgements.json
# from Package.resolved (exact pins) and each package's LICENSE/NOTICE in Xcode's
# SourcePackages checkout. Run via `make licenses`; CI runs it and fails on a diff.
#
# Fails on a licence it can't classify as permissive, so a new dependency needs
# a human decision (and a docs/decisions.md entry) before it ships.
#
# SOURCE_PACKAGES can point at a SourcePackages dir; by default the newest
# FoodPlanner-* DerivedData entry that has a checkouts/ folder is used.
set -euo pipefail
cd "$(dirname "$0")/.."

RESOLVED="FoodPlanner.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved"
if [ -z "${SOURCE_PACKAGES:-}" ]; then
  SOURCE_PACKAGES="$(ls -dt "$HOME"/Library/Developer/Xcode/DerivedData/FoodPlanner-*/SourcePackages 2>/dev/null | head -1 || true)"
fi
[ -d "${SOURCE_PACKAGES:-}/checkouts" ] || {
  echo "No SourcePackages/checkouts found. Build once in Xcode (or run 'make build'), or set SOURCE_PACKAGES." >&2
  exit 1
}

python3 -I - "$RESOLVED" "$SOURCE_PACKAGES/checkouts" <<'PY'
import json, os, sys

resolved, checkouts = sys.argv[1], sys.argv[2]
pins = sorted(json.load(open(resolved))["pins"], key=lambda p: p["identity"])

def read(path):
    with open(path, encoding="utf-8", errors="replace") as f:
        return f.read().replace("\r\n", "\n").strip("\n") + "\n"

def classify(text):
    t = text.lower()
    if "apache license" in t and "version 2.0" in t:
        return "Apache-2.0"
    if "redistribution and use in source and binary forms" in t and "neither the name" in t:
        return "BSD-3-Clause"
    if "provided 'as-is'" in t and "permission is granted to anyone to use this software" in t:
        return "Zlib"
    if "permission is hereby granted, free of charge" in t:
        return "MIT"
    return None

entries = []
for pin in pins:
    ident = pin["identity"]
    version = pin["state"].get("version") or pin["state"].get("revision", "")[:12]
    # checkouts are named after the repo, which may differ in case from the identity
    dirs = {d.lower(): d for d in os.listdir(checkouts)}
    d = dirs.get(ident.lower())
    if d is None:
        sys.exit(f"{ident}: no checkout found in {checkouts}")
    base = os.path.join(checkouts, d)
    files = sorted(os.listdir(base))
    lic = next((f for f in files if f.lower().startswith(("license", "copying"))), None)
    if lic is None:
        sys.exit(f"{ident}: no LICENSE file")
    text = read(os.path.join(base, lic))
    spdx = classify(text)
    if spdx is None:
        sys.exit(f"{ident}: licence not recognised as permissive; review it, then teach classify()")
    notice = next((f for f in files if f.lower().startswith("notice")), None)
    entries.append({
        "name": d,
        "version": version,
        "url": pin["location"].removesuffix(".git"),
        "license": spdx,
        "licenseText": text,
        "notice": read(os.path.join(base, notice)) if notice else None,
    })

md = ["<!-- Generated by scripts/generate-third-party-licenses.sh (make licenses). Do not edit. -->\n",
      "# Third-party licences\n",
      "FoodPlanner uses the open-source packages below. Each is licensed under its own terms, reproduced here.\n"]
for e in entries:
    md.append(f"## {e['name']} {e['version']}\n")
    md.append(f"- Source: {e['url']}\n- Licence: {e['license']}\n")
    md.append("```text\n" + e["licenseText"].rstrip("\n") + "\n```\n")
    if e["notice"]:
        md.append("NOTICE:\n\n```text\n" + e["notice"].rstrip("\n") + "\n```\n")
open("THIRD-PARTY-LICENSES.md", "w").write("\n".join(md))

with open("FoodPlanner/Resources/Acknowledgements.json", "w") as f:
    json.dump(entries, f, indent=2, ensure_ascii=False)
    f.write("\n")
print(f"Wrote licences for {len(entries)} packages")
PY
